### ISSUE TITLE
一点疑问

### ISSUE THREAD

**Issue by kavience** [ImSingee/payjs_test#1]
payjs可以用于个人小程序吗？

**Comment by ImSingee** [comment]
可以，不过注意一下是跳转的方式实现的
在 2018年12月12日 +0800 PM3:01，kavience <notifications@github.com>，写道：

**Comment by kavience** [comment]
我看源码是用wx.navigateToMiniProgram，而不是微信官方的wx.requestPayment，是吗？

**Comment by ImSingee** [comment]
> 我看源码是用 wx.navigateToMiniProgram，而不是微信官方的 wx.requestPayment，是吗？

对，是通过跳转到其他小程序支付再跳回来实现的。难道你不是从 [PAYJS](https://payjs.cn/ref/WDQGQD) 的官方文档进来的吗？这个是我给它写的 demo……

**Comment by kavience** [comment]
好的，明白了，谢谢哈

**Comment by Elegent** [comment]
跳转到 PAYJS 小程序成功 {errMsg: "navigateToMiniProgram:ok"

**Comment by BWmelon** [comment]
小程序提交审核时提示个人小程序不允许使用支付功能，想问一下用payjs时如何通过审核

https://cdn.payjs.cn/6008e881d3001
