### ISSUE TITLE
请问小程序个人云开发 可以使用PAYJS支付吗？

### ISSUE THREAD

**Issue by yxw699** [ImSingee/payjs_test#10]
请问小程序个人云开发 可以使用PAYJS支付吗？
非常感谢

**Comment by ImSingee** [comment]
单纯依靠云开发好像不行，因为我记得云开发不能接收外部通知（webhook）

不过你可以使用其他 FaaS 类服务实现接收到 payjs 通知后调用云开发 API 进行支付完成的逻辑
