### ISSUE TITLE
没有商户号

### ISSUE THREAD

**Issue by benxiong2** [ImSingee/payjs_test#12]
最后支付跳转显示mchid不存在或错误，大佬这个怎么处理？

**Comment by ImSingee** [comment]
商户号正常填写了吗

**Comment by ImSingee** [comment]
https://github.com/ImSingee/payjs_test/blob/master/utils/util.js#L2

这里的 mchid 和 secret 都需要填写自己的

**Comment by benxiong2** [comment]
const mchid = '160xxxxx'和
const secret = 'Lxkxxxxx'x'x'x'我都填写了

**Comment by benxiong2** [comment]
新手不大会搞代码，还请大佬见谅

**Comment by ImSingee** [comment]
那联系 payjs 客服询问吧，可能是没开通小程序支付？
