### ISSUE TITLE
企业主体的小程序可以使用吗？

### ISSUE THREAD

**Issue by Leawee** [ImSingee/payjs_test#3]
我的是企业主体但未开通微信支付的小程序，不想开通微信支付，可以用你这个来实现吗？

**Comment by ImSingee** [comment]
可以的，具体问题还请点击首页的 PAYJS 链接注册登录后发工单询问

**Comment by Leawee** [comment]
我感觉他们的客服一点都不专业，一会说可以，一会说不可以，一会又说ios不可用。直接把我搞懵了，我就来这里以提issue的形式来请教一下您

**Comment by ImSingee** [comment]
小程序支付禁止 iOS 虚拟支付，因此也无法使用 PAYJS

如果在 PAYJS 拥有企业主体的商户号，那么是可以登录微信商户后台的，然后完成 MA 授权可以直接开通官方的小程序支付

**Comment by Leawee** [comment]
不是用于虚拟支付，是购买实物。
现在是不想开通微信支付，如果开通微信支付的话就直接用官方的支付接口就行了。
现在就是说如果这个企业主体的小程序不开通微信支付，也可以使用你这个进行支付吗？

**Comment by ImSingee** [comment]
可以，但是 iOS 可能无法支付，具体还是需要联系 PAYJS
